### ISSUE TITLE
Please update to the latest jsdoc.

### ISSUE THREAD

**Issue by rootical** [jsBoot/gulp-jsdoc#28]
I am using commentsOnly plugin and it has major problems which were resolved in the recent versions of  jsdoc.  More info here: http://stackoverflow.com/a/28706783/1200683 
Thanks

**Comment by hegemonic** [comment]
Hey, I'm the maintainer of JSDoc. JSDoc 3.3.0 has been released, so it would be super-helpful if you could pick up the current version. Thanks!

**Comment by dmp42** [comment]
Hi @hegemonic 

Thanks for the heads-up.
I'll try to have a look soon.

**Comment by tychotatitscheff** [comment]
I would +1 this :)

**Comment by mattsawyer77** [comment]
+1

**Comment by adisuryadi** [comment]
+1

**Comment by liammagee** [comment]
+1

**Comment by klausbayrhammer** [comment]
+1

**Comment by tnguyen14** [comment]
any update on when this will happen?

**Comment by mlucool** [comment]
+1

**Comment by mlucool** [comment]
Hi all,

I have created a new version of jsdoc that attempts to just pass a config to the jsdoc cli and the files come from the files passed in via gulp. See its [notes](https://github.com/mlucool/gulp-jsdoc3#notes).  You can check it out here: https://github.com/mlucool/gulp-jsdoc3

Although there are directions for npm, I have not yet release it - so you'll have to use it as git dependency. Any comments would be helpful before I publish to npm.

@dmp42 I would be happy to make a pull request into this, but it is a total re-write with no copied code. Given that, its totally up to you if you want to maintain a rewrite (that is if you even still use jsdoc, which you comments suggest otherwise).

Thanks,
Marc

**Comment by indexzero** [comment]
Please do. This project is looking for new maintainers. We can discuss more from the perspective of the code itself.

**Comment by mlucool** [comment]
This repo seems to not be maintained. What are the feelings about starting fresh?

**Comment by dmp42** [comment]
I shamelessly lost interest in this, and gave @indexzero maintainers rights.

I'm happy to have more people taking over the project, either here, or on another repo, whichever is best for people.

**Comment by mlucool** [comment]
I'd rather own the repo then if none of the previous owners are interested. Do you mind if I post a note on the readme pointing to it?

**Comment by mlucool** [comment]
Released here https://www.npmjs.com/package/gulp-jsdoc3

**Comment by hbetts** [comment]
Given some of the community frustrations detailed in #18 could we move forward with deprecating this package, including closing down the issues/pull-request pages?

**Comment by mlucool** [comment]
@dmp42 can you please follow:
http://stackoverflow.com/questions/22457959/current-best-practice-for-retiring-a-project-on-github-and-npmjs-org
See also: https://docs.npmjs.com/cli/deprecate

I have created: https://github.com/jsBoot/gulp-jsdoc/pull/32 to make the README clear, but feel free to change it to anything you wish.

**Comment by dmp42** [comment]
@indexzero would you go ahead and deprecate on npm?

**Comment by mlucool** [comment]
@indexzero in addition, will you also release this one more time so npm shows the correct README.

**Comment by indexzero** [comment]
@mlucool @dmp42 adding this towards the top to my backlog of open source maintenance.

**Comment by mlucool** [comment]
@indexzero @dmp42 just a reminder

**Comment by hipio** [comment]
@indexzero @dmp42 This project is still not marked as deprecated on NPM, just a small reminder.

**Comment by indexzero** [comment]
This is done.

**Comment by indexzero** [comment]
@dmp42 can you shutdown the issues and pull-requests on this repo? I do not have access to this.

**Comment by dmp42** [comment]
@indexzero will do after this comment in 3... 2... 1...
